# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robotics_messages_v2.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'robotics_messages_v2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1arobotics_messages_v2.proto\x12\x08robotics\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n\x04Ping\x12\x34\n\x10\x63lient_timestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"r\n\x04Pong\x12\x34\n\x10\x63lient_timestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x10server_timestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xc7\x01\n\tTelemetry\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x1b\n\x13temperature_celsius\x18\x02 \x01(\x02\x12\x13\n\x0b\x63pu_percent\x18\x03 \x01(\x02\x12\x16\n\x0ememory_percent\x18\x04 \x01(\x02\x12\x14\n\x0c\x64isk_percent\x18\x05 \x01(\x02\x12\x16\n\x0euptime_seconds\x18\x06 \x01(\x04\x12\x18\n\x10software_version\x18\x07 \x01(\t\x12\x15\n\rmodel_version\x18\x08 \x01(\t\"\xb9\x01\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1e\n\x04ping\x18\n \x01(\x0b\x32\x0e.robotics.PingH\x00\x12\x1e\n\x04pong\x18\x0b \x01(\x0b\x32\x0e.robotics.PongH\x00\x12(\n\ttelemetry\x18\x14 \x01(\x0b\x32\x13.robotics.TelemetryH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robotics_messages_v2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PING']._serialized_start=73
  _globals['_PING']._serialized_end=133
  _globals['_PONG']._serialized_start=135
  _globals['_PONG']._serialized_end=249
  _globals['_TELEMETRY']._serialized_start=252
  _globals['_TELEMETRY']._serialized_end=451
  _globals['_MESSAGE']._serialized_start=454
  _globals['_MESSAGE']._serialized_end=639
# @@protoc_insertion_point(module_scope)
